### ISSUE TITLE
Are there any current plans to support Azure DevOps Server

### ISSUE THREAD

**Issue by olcayseker** [microsoft/azure-devops-extension-cascading-picklist#113]
Is there an update to the API that stops this extension from being used on on-premises servers?

**Comment by AminTi** [comment]
It is expected that the solution should be compatible with on-premises servers, can you describe your environment?

**Comment by olcayseker** [comment]
The information about the on-prem environment version is as follows.

![2023-05-30_14-34](https://github.com/microsoft/azure-devops-extension-cascading-picklist/assets/776387/3ce04871-6195-4244-b0e7-9cb7897b109c)

When I enter the marketplace for installation, it warns that it is not suitable and does not install.

![2023-05-30_14-36](https://github.com/microsoft/azure-devops-extension-cascading-picklist/assets/776387/e1f08309-c224-46e3-b1c6-99261ad6d8b8)

**Comment by AminTi** [comment]
Hi there! I've checked the "targets," and unfortunately, the Cascading picklist doesn't work with on-premises solutions at the moment, and we have no plans to add support for on-premises solutions in the near future.

**Comment by njpaul** [comment]
@AminTi My company needs an extension like this on-prem, so I built this extension modified to target `"Microsoft.VisualStudio.Services"` and tested against Server 2022. It works great as far as I can tell. Are you able to elaborate on what API(s) were missing, because they seem to exist now. I don't know about previous versions.

I'd like to avoid forking this extension for the sole purpose of installing on-prem, if possible.

**Comment by AleXSR700** [comment]
Did anybody make any progress on this? I am also interested in this extension but we are too using on-premises server instead of service.
