### ISSUE TITLE
Updaing the JSON in Config File via API??

### ISSUE THREAD

**Issue by greerlcourtney** [microsoft/azure-devops-extension-cascading-picklist#37]
Is there anyway to update the JSON in the config file from code? Our team is making sure that any picklist value that changes can be automatically remapped. Is there an API built to access the config file?

**Comment by ByAgenT** [comment]
Hello @greerlcourtney. 

You can update config file by directly writing to the extension storage. You can take a look at the [link](https://docs.microsoft.com/en-us/azure/devops/extend/develop/data-storage?view=azure-devops#advanced) that will give you the information how extension storage is working. If you will be able to establish REST calls to data storage endpoints, you can refer to [this code](https://github.com/microsoft/azure-devops-extension-cascading-picklist/blob/master/src/common/storage.service.ts#L61) and you will find out how extension creates a key for storing config. In short it's just a concatenation of config type (which is manifest) and project ID separated by "|". 

If you will stuck in finding the endpoint for updating storage, you can also analyze what network calls happens when you save the config in developer tools of your browser.

**Comment by greerlcourtney** [comment]
Thank you so much!
