### ISSUE TITLE
Not able to query childlist values from the REST DevOps API using a parent picklist value

### ISSUE THREAD

**Issue by jayde3m** [microsoft/azure-devops-extension-cascading-picklist#47]
Using the example supplied and instructions from the Readme, "You can use List Fields REST API if you need help finding the value.", its not clear how I can query for the child picklist based on a supplied parent picklist value.
i.e. If I request from the API and pass value 'Release Blue',  I want the response to return allowed values ['Blue1','Blue2','Blue3'] 

{
  "version": 1,
  "cascades": {
      "Custom.MajorRelease": {
          "Release Blue": {
              "Custom.MinorRelease": [
                  "Blue.1",
                  "Blue.2",
                  "Blue.3"
              ]
          },
          "Release Red": {
              "Custom.MinorRelease": [
                  "Red.A",
                  "Red.B",
                  "Red.C"
              ]
          }
      }
  }
}

**Comment by jayde3m** [comment]
cc @ByAgenT

**Comment by ByAgenT** [comment]
Hey @jayde3m. List Fields REST API can only help you get list of fields with reference names that are needed for cascading configuration. You can't get anything about cascades from List Fields REST API, because cascading configuration stored in extension storage.
If you want to access or change cascade configuration programmatically, refer to [this issue](https://github.com/microsoft/azure-devops-extension-cascading-picklist/issues/37).

**Comment by jayde3m** [comment]
Thanks @ByAgenT, calling the ExtensionManagement API worked perfectly to retrieve the JSON collection of cascading data.
